# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCode',
            fields=[
                ('CheckCodeId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserPhone', models.CharField(max_length=255)),
                ('CheckCode', models.CharField(max_length=255)),
                ('SendTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('CircleId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('Information', models.CharField(max_length=255)),
                ('Picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CircleComment',
            fields=[
                ('CommentId', models.IntegerField(primary_key=True, serialize=False)),
                ('CircleId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('Comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('LabelId', models.IntegerField(primary_key=True, serialize=False)),
                ('Label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SendHezu',
            fields=[
                ('SendHezuId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('Information', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Picture', models.CharField(max_length=255)),
                ('Number', models.IntegerField()),
                ('Delete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('PassWord', models.CharField(max_length=255)),
                ('UserPhoto', models.CharField(max_length=255)),
                ('TrueName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('UserPhone', models.CharField(max_length=255)),
                ('Label1', models.CharField(max_length=255)),
                ('Label2', models.CharField(max_length=255)),
                ('Label3', models.CharField(max_length=255)),
            ],
        ),
    ]
